name: VyOS LTS Build

on:
#  push:
#    tags:
#      - "*"
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "1.3.7"
        description: VyOS version
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For VyOS 1.4 (sagitta) use vyos/vyos-build:sagitta
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:equuleus
      env:
        TZ: Europe/Stockholm
      options: --privileged
    env:
      TZ: Europe/Stockholm
    permissions:
      actions: read
      contents: write

    steps:
      - name: Git clone vyos-build
        run: |
          set -eux
          
          git clone -b 1.3.7 --single-branch https://github.com/vyos/vyos-build

      - name: Cleanup env
        working-directory: vyos-build
        run: |
          set -eux

          make clean

      - name: Make ISO
        working-directory: vyos-build
        run: |
          set -eux
          
          ./build-vyos-image iso \
            --architecture "amd64" \
            --build-by "test@test.local" \
            --build-type "release" \
            --version "${{ inputs.version }}"

      - name: ls
        run: |
          set -eux

          pwd
          ls -lah
          ls -lah vyos-build/build

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          name: VyOS ${{ inputs.version }} LTS
          tag_name: ${{ inputs.version }}
          body: |
            VyOS ${{ inputs.version }} LTS
          draft: true
          prerelease: true
          files: |
            vyos-build/build/vyos-${{ inputs.version }}-amd64.iso
